### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by LostExcalibur** [LeaPhant/skyblock-stats#55]
I get this output when running npm start, does anyone know whats going on ? Googling 'redis ECONNREFUSED' doesnt bring me anywhere.
```
C:\Users\MyName\Gitrepos\skyblock-stats>npm start

> skyblock-stats@1.0.0 start C:\Users\MyName\Gitrepos\skyblock-stats
> node init && node index

Running SkyBlock Stats on 4 cores
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (C:\Users\MyName\Gitrepos\skyblock-stats\node_modules\redis\index.js:341:14)
    at Socket.<anonymous> (C:\Users\MyName\Gitrepos\skyblock-stats\node_modules\redis\index.js:222:14)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skyblock-stats@1.0.0 start: `node init && node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skyblock-stats@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MyName\AppData\Roaming\npm-cache\_logs\2020-06-15T15_22_36_764Z-debug.log```

**Comment by LeaPhant** [comment]
You need to install Redis, I forgot to put it into dependencies. It's not used right now but will be used soon.

**Comment by LostExcalibur** [comment]
Thank you so much, it works now ! If you add redis to the list of requirements, consider adding a line saying you need to run redis-server. Anyways ty for everything !

**Comment by LeaPhant** [comment]
Glad you got it working!! :) will add a line
