### ISSUE TITLE
I followed the steps but I'm getting this error.

### ISSUE THREAD

**Issue by DemonMildzz** [LeaPhant/skyblock-stats#56]
```
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)
Emitted 'error' event at:
    at RedisClient.on_error (C:\Users\swaim\sbstats\node_modules\redis\index.js:341:14)
    at Socket.<anonymous> (C:\Users\swaim\sbstats\node_modules\redis\index.js:222:14)
    at Socket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skyblock-stats@1.0.0 start: `node init && node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skyblock-stats@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\swaim\AppData\Roaming\npm-cache\_logs\2020-06-26T13_29_38_244Z-debug.log
```

**Comment by metalcupcake5** [comment]
Do you have a redis server?

**Comment by DemonMildzz** [comment]
Oh I'm so sorry, I forgot to run it!
