### ISSUE TITLE
unhandledRejection TypeError: Cannot read property 'filter' of undefined     at init (/www/wwwroot/guild.psychoesclipe.com/skyblock-stats-master/src/lib.js:2502:62)

### ISSUE THREAD

**Issue by luanmenglei** [LeaPhant/skyblock-stats#75]
unhandledRejection TypeError: Cannot read property 'filter' of undefined
    at init (/www/wwwroot/guild.psychoesclipe.com/skyblock-stats-master/src/lib.js:2502:62)

**Comment by luanmenglei** [comment]
on running "const collectionData = constants.collection_data.filter(a => a.skyblockId == itemType)[0];"

**Comment by LeaPhant** [comment]
That error can be ignored and shouldn't cause any issues, but I gotta fix it eventually lol.
