### ISSUE TITLE
Redis Issues

### ISSUE THREAD

**Issue by JakeyPrime** [LeaPhant/skyblock-stats#92]
Happens shortly after looking up pretty much anyone, but happens with different Redis keys each time. 

```
/home/Skyblock/node_modules/redis-parser/lib/parser.js:179
    return new ReplyError(string)
           ^

ReplyError: ERR value is not an integer or out of range
    at parseError (/home/Skyblock/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/home/Skyblock/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'zremrangebyrank',
    args: [ 'lb_auctions_bought_common', '0', 'NaN' ]
  }
}```

**Comment by LeaPhant** [comment]
Should be fixed! if you don't use the start script you might have to run `node init` in the project root manually to fix it on your instance.
Thanks for reporting.
